packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  vue-demi: set this to true or false

# Allow these dependencies to run install/build scripts (native/binary setup).
onlyBuiltDependencies:
  - esbuild
  - '@parcel/watcher'
  - vue-demi
