<?php

namespace app\admin\controller;

use think\Controller;
use think\Model;
use think\Request;

class Index extends Controller
{

    protected function initialize()
    {

        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        // 查询用户信息
        session(['prefix' => 'admin_',]);
        $id = session('user.id');

        if (empty($id) & !empty(cookie('admin_user')))
            $id = cookie('admin_user')['id'];

        $admin = model('AdminModel')
            ->where('id', $id)
            ->find();

        $head = md5(trim(strtolower($admin['email'])));

        return view()
            ->assign([
                'admin' => $admin,
                'head' => $head
            ]);
    }

    public function welcome()
    {
        return view();
    }
}
