// Hand-written ergonomic aliases over the generated OpenAPI schema.
// The schema itself is generated by `pnpm gen:api` (openapi-typescript) from
// backend/docs/swagger.json.
import type { components } from './schema'

export type * from './schema'

type Schemas = components['schemas']

export type Post = Schemas['http.postResponse']
export type PostListResponse = Schemas['http.listResponse']
export type LoginRequest = Schemas['http.loginRequest']
export type SavePostRequest = Schemas['http.savePostRequest']
export type TokenResponse = Schemas['http.tokenResponse']
export type UserResponse = Schemas['http.userResponse']
export type RenderRequest = Schemas['http.renderRequest']
export type RenderResponse = Schemas['http.renderResponse']
export type ErrorResponse = Schemas['http.errorResponse']

export type Category = Schemas['http.categoryResponse']
export type CategoryListResponse = Schemas['http.categoryListResponse']
export type SaveCategoryRequest = Schemas['http.saveCategoryRequest']
export type Tag = Schemas['http.tagResponse']
export type TagListResponse = Schemas['http.tagListResponse']
export type SaveTagRequest = Schemas['http.saveTagRequest']
export type Comment = Schemas['http.commentResponse']
export type CommentListResponse = Schemas['http.commentListResponse']
export type CreateCommentRequest = Schemas['http.createCommentRequest']
export type ModerateCommentRequest = Schemas['http.moderateCommentRequest']
export type SiteSettings = Schemas['http.settingsResponse']
export type UpdateSettingsRequest = Schemas['http.updateSettingsRequest']
